<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 17.01.20
 * Time: 21:58
 */

namespace app\modules\api\components;


use yii\rest\Controller;
use yii\web\Response;

class ApiModuleController extends Controller
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}