version: '2'
services:

  php:
    build: php
    container_name: php
    restart: unless-stopped
    volumes:
    - ./../www:/app
    - ./../composer-docker/cache:/root/.composer/cache:delegated
    links:
    - mariadb:mariadb

  nginx:
    build: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
    - 8080:80
    volumes:
    - ./../www/:/app
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - php

  mariadb:
    build: mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
    - ./../mariadb-data:/var/lib/mysql
    ports:
    - 33060:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=yii2
    - MYSQL_USER=yii2
    - MYSQL_PASSWORD=opopOPOPop111